### ISSUE TITLE
How to schedule automated recording.

### ISSUE THREAD

**Issue by WEDOBROADCAST** [MyCometG3/recDL#1]
Hi,

great app as i'm using it for most of my h.264 recording nowdays with decklink. would be great if can add scheduling features

Thanks

**Comment by MyCometG3** [comment]
Hi,
Thank you for trying my small app, recDL!

Basically it does not provide any scheduling interface by itself though, 
you can do it using Automator + Calendar + AppleScript combination.

///***///

For Scheduling AppleScript task, you can see some websites and/or YouTube at:
> https://www.bing.com/search?q=automator+calendar+applescript

Also Automator Users Guide webpage from Apple is following:
> https://support.apple.com/guide/automator/welcome/mac

///***///

For Scripting using AppleScript, open script editor.app and try following

Sample: "Record 10 min and autoquit, and 4 sec preview"
```
tell application "recDL"
	set videoPreview to true
	set audioPreview to true
	start recording limit in seconds 10 * 60 with autoQuit
	delay 4
	set videoPreview to false
	set audioPreview to false
end tell
```
///***///

I hope this would help your request.

Best regards,
MyCometG3

**Comment by WEDOBROADCAST** [comment]
Hi,

thank you for the information. One more question how to set deinteralce for
h.264 encoding? There is different between blackmagic media express and
recDL when recording video that have news ticker as we can see the jaggered
interlace in recDL but not in blackmagic media express.

Thanks

**Comment by MyCometG3** [comment]
Hi,
recDL is mainly build for casual capturing movie clips. It does not de-interlace any source when transcoding but preserve interlaced state as is. (Interlaced video is tagged as interlaced track, instead of progressive track)

If you use interlaced source, I recommend any open source encoder software. For example,
```
ffmpeg - command line utility
Handbrake - GUI based encoder utility
```
These software can apply Decomb/Deinterlace filters. I strongly recommend them because there are so many users of those software and you can find huge QA over internet.

On the other-hand, I commonly captured SD interlaced sources in ProRes422LT, and I use my command line utility movencoder2 to deinterlace using following options:
```
$ movencoder2 -verbose \
    -mevf "format=yuv444p,crop=704:480:8:2,yadif=0:-1:0,pp=dr,unsharp=5:5:0.50:5:5:0.5,hqdn3d=2.0,format=yuv420p" \
    -meve "c=libx264;r=30000:1001;par=40:33;b=1.5M;o=preset=medium:profile=main" \
    -mex264 "level=4.1:vbv-maxrate=50000:vbv-bufsize=62500:keyint=60:min-keyint=6:bframes=3" \
    -ae "encode=y;codec=aac;bitrate=192k" \
    -in /Users/foo/Movies/cam.mov \
    -out /Users/foo/Movies/out.mov
```
Most options could be translated into ffmpeg filter definition and encoding options but I am not good at using ffmpeg in detail.

**Comment by WEDOBROADCAST** [comment]
Thank you for the explanation. One more question how can i get the capture audio volume if i wanted to add VU meter or audio meter in the app?

Thanks
