### ISSUE TITLE
timecode does not work

### ISSUE THREAD

**Issue by kisso** [MyCometG3/recDL#2]
hi, I am trying to record with settings
```
keyValues[Keys.timeCodeFormat] = 32/64      // 0:None, 32:tmcd, 64:tc64
```

but I am getting errors like:
```
ERROR: Could not write video sample buffer.(AVAssetWriterStatus.Failed)
ERROR: Could not write timecode sample buffer.(AVAssetWriterStatus.Failed)
ERROR: Could not write audio sample buffer.(AVAssetWriterStatus.Failed)
```

when I use:
```
keyValues[Keys.timeCodeFormat] = 0      // 0:None, 32:tmcd, 64:tc64
```

I have no problems

**Comment by MyCometG3** [comment]
Do you see this issue even after DLABCaptureManager issue#6 fixes applied?
I want to know if the fix (CMSampleTimingInfo for timecodeSample) helped or not.

**Comment by kisso** [comment]
I fixed it this way is it ok?
```
status = CMSampleBufferCreate(kCFAllocatorDefault,
                                      dataBuffer,
                                      true,
                                      NULL,
                                      NULL,
                                      description,
                                      1,
                                      1,
                                      &timingInfo,
                                      1,
                                      &sizes,
                                      &sampleBuffer);
```
Instead of &timingInfo there was timingInfoTMP which was initialized with {0}. after making this change I am not getting error anymore, but when I try to recieve presentationalTimestamp, I am getting timestamp counted from start of the video, not from start of recording.

**Comment by MyCometG3** [comment]
Thank you.
Yes, it is. It works as expected now.
I confirmed that this issue is not issue in recDL codebase.

//

You may confuse b/w presentation timestamp and timecode.

- Every media(video/audio/timecode) track contains media data blockbuffer in CMSampleBuffer; PresentationTimeStamp means "timestamp for video stream, zero offset".
- Timecode track encapsulates timecode blockbuffer: Timecode is "timestamp for video source, offset value depends on timecode generator".
- Some DeckLink HW supports either SERIAL, RP188, VITC timecode. RP188 and VITC are embed into video stream.

I guess you may want timecode track even if source does not provide any timecode. In such case you need to create custom timecode from scratch by yourself. 
Apple's sample code AVTimeCodeReadWrite or AVTimedAnnotationWriter may help.
