### ISSUE TITLE
"No such module 'DLABridging'"

### ISSUE THREAD

**Issue by TVTA-YT** [MyCometG3/recDL#3]
This issue shows up when trying to compile the program in Xcode. It seems to only affect the "RDL1Recording" file. DLABridging is there, but for some reason, Xcode isn't recognizing it.

**Comment by MyCometG3** [comment]
1) Check "Project navigator - recDL - Frameworks - DLABridging" ... Is it displayed in red letters?
If so, you need to tell xcode where the framework path is, see inspector + change the path-to accordingly.
But I recommend you remove the existing missing framework entry under project navitgator, then drag and drop your own framework(s) instead. It would work as expected.

Note - Your own frameworks must be signed with your own ID first.

2) Note that this recDL xcode project is built as "Embed & Sign" both DLABCaptureManager.framework and DLABridging.framework into application bundle. You can see the pre-built binary embed in the release dmg file.
If you want, you can place your framework(s) in ~/Library/Frameworks/ as the private framework bundle(s).
You will need to build your own framework(s) and sign with your own ID.

If you are not familiar with legacy library management, you should try the DLAB Swift package instead of the DLABridging/DLABCaptureManager frameworks. DLAB is the S.P. version of DLABridging/DLABCaptureManager.

**Comment by TVTA-YT** [comment]
1. Both DLABridging and DLACaptureManager are displayed in red. I'm not familiar with building my own frameworks. Is there any place to get both frameworks?
2. I do not see a DMG file. Where can I find the DLAB Swift package?

**Comment by MyCometG3** [comment]
1. You can find DLABridging.framework and DLABCaptureManger.framework in my github projects
2. Use xcode workspace and put DLABridging/DLABCaptureManger/recDL into it, then update dependencies accordingly.
3. Build all.

Anyway, I think this issue seems to be not issue of my project itself. Close.
